### ISSUE TITLE
Auto Hunt error

### ISSUE THREAD

**Issue by shekemo** [akiva0003/eSim#13]
Auto Hunt Error

**Comment by shekemo** [comment]
![orca-image--902764606](https://user-images.githubusercontent.com/82989096/231022772-5c73a795-400c-4f0d-b8a2-755b846e4109.jpeg)
Erorr bRo

**Comment by shekemo** [comment]
![orca-image-1969180866](https://user-images.githubusercontent.com/82989096/231022961-68b1d2b4-f100-4fc5-84df-fbd2b4ff1ac2.jpeg)
This is the error what im talking About

**Comment by akiva0003** [comment]
I guess the bot was logged out, probably because you were playing in your browser at the same time.
For the next time: use `.update nick` and `.limits nick` and try again.

**Comment by shekemo** [comment]
Okeyy Thank you 👑
